const cv = [
  {
    job: "Frontend development student",
    date: "From July 2022 till present",
    company: "SheCodes.io, etc.",
    company_desc:
      "Coding workshops to learn the latest coding frameworks, libraries and technologies.",
    description: [
      "Focusing on learning React.js and Angular and creating customer-centric experiences",
    ],
    industry: "Bootcamp",
    keywords: [
      "Responsive Web Design",
      "Git",
      "JavaScript",
      "Cascading Style Sheets (CSS)",
      "HTML",
      "Bootstrap",
      "React.js",
      "Frontend Development",
      "Web Design",
      "TypeScript",
      "jQuery",
      "Node.js",
    ],
  },
  {
    job: "User Happiness Manager",
    date: "From Aug 2021 till July 2022",
    company: "Remote.com",
    company_desc:
      "Remote helps companies of all sizes employ full-time and contract workers around the world by taking care of international payroll, benefits, taxes, and compliance in dozens of countries.",
    description: [
      "Handle high amounts of live chat and phone calls",
      "Identify and evaluate customers' needs to deliver satisfaction",
      "Provide accurate, valid and comprehensive information to customers",
      "Manage complaints, provide proper solutions and options within the time limits; follow up to secure resolution",
    ],
    industry: "Saas",
    keywords: [
      "Customer Relationship Management",
      "Customer Experience",
      "Customer Insight",
      "Customer Retention",
      "Customer Experience Management",
      "Customer Loyalty",
      "Customer Onboarding",
      "Customer Satisfaction",
      "Zendesk",
      "Notion",
      "GitLab",
      "DocuSign",
      "Zoom",
      "Loom",
      "Miro",
      "Slack",
    ],
  },
  {
    job: "Customer Success Advisor",
    date: "From Apr 2020 till Aug 2021",
    company: "Remo.co",
    company_desc:
      "Remo is an environment for virtual gatherings, conferences, remote and distributed teams. It fosters real-time collaboration, strengthens company culture and helps develop deep and meaningful relationships allowing anyone to participate in the digital economy.",
    description: [
      "Manage customer health along the customer journey",
      "Educate customers on the product, value, and performance",
      "Make the onboarding process simpler and easier to handle",
      "Driving product adoption and converting power users to champions",
    ],
    industry: "Sass",
    keywords: [
      "Customer Product Training",
      "Customer Experience",
      "Customer Retention",
      "Customer Experience Management",
      "Customer Loyalty",
      "Customer Onboarding",
      "Customer Satisfaction",
      "Strategic Planning",
      "Crisp",
      "Notion",
      "Miro",
      "Typeform",
      "ChargeBee",
      "Stripe",
      "Loom",
      "Wordpress",
      "Reform",
      "Slack",
    ],
  },
  {
    job: "Country Manager for Latin America & Spain",
    date: "From Sept 2017 till Jan 2020",
    company: "Joom.com",
    company_desc:
      "Joom is one of the fastest-growing international eCommerce platforms in Europe. Its mission is to let people everywhere shop for anything at the best prices. To achieve it, Joom cuts out all the middlemen and brings together factories and merchants across the globe to sell straight to customers.",
    description: [
      "Manage every aspect of support operations in-country/region",
      "Build credibility at various levels and enhance the user life cycle",
      "Implement and improve processes for the customer support representatives",
      "Manage agents' hiring, training, coaching, terminations, etc.",
    ],
    industry: "e-Commerce",
    keywords: [
      "Program Management",
      "Operations Management",
      "Logistics Management",
      "Customer Service Management",
      "Marketing Management",
      "Customer Experience Management",
      "Project Management",
      "Analytical Skills",
      "Business Development",
      "Intercom",
      "FreshDesk",
      "Jira",
      "Confluence",
      "Notion",
      "CrowdIn",
      "Miro",
      "Skype",
    ],
  },
  {
    job: "Customer Support Lead",
    date: "From Oct 2015 till Aug 2017",
    company: "RJ Games",
    company_desc:
      "RJ Games was founded in 2012 and is an ambitious social & mobile game Publisher and Developer that released social games like Dakota and Under Control.",
    description: [
      "Handle high amounts of live chat with players",
      "Identify and evaluate players' needs to deliver satisfaction",
      "Handle incidents and communicate changes",
    ],
    industry: "Gaming",
    keywords: [
      "Technical Support",
      "Technical Documentation",
      "Troubleshooting",
      "Technical Assistance",
      "Zendesk",
      "Jira",
      "Confluence",
      "Slack",
      "G-suite",
    ],
  },
  {
    job: "Customer Success Advisor",
    date: "From Sept 2013 till Aug 2015",
    company: "2wTRADE",
    company_desc:
      "2WTRADE is a pioneer company in the area of e-Commerce that implements modern technological infrastructure to manage direct sales on a global scale.",
    description: [
      "Developing and sustaining solid relationships with key merchants that bring in the most income for the company",
      "Acting as the main point of contact between key merchants and internal teams",
      "Communicating and collaborating with the advertising, design, marketing, sales, and logistics departments to ensure that key merchants needs are met",
    ],
    industry: "e-Commerce",
    keywords: [
      "Program Management",
      "Operations Management",
      "Logistics Management",
      "Customer Service Management",
      "Marketing Management",
      "Customer Experience Management",
      "Project Management",
      "Analytical Skills",
      "Business Development",
      "Skype",
      "G-suite",
    ],
  },
  {
    job: "History and Mass Media Student",
    date: "2010/2014 & 2015/2017",
    company: "RUDN",
    company_desc:
      "Peoples' Friendship University of Russia (RUDN) is an international classical university with 7 faculties, 10 institutes, 156 research labs and 4 centres of collective use. Alma mater of students from 152 countries of the world that offers 18 Bachelor’s and Master’s educational programs with international accreditation.",
    description: [
      "These degrees were focused on the critical understanding of the human experience",
      "Through the study of history and mass media, students develop an understanding of who we are, where we came from, how and why our society has changed over time and how humans have interacted with each other and with the natural world",
      "Students can choose a subject to depend their studies: Archaeology, Ethnography, Classical History, Mass Media, others",
    ],
    industry: "history",
    keywords: [
      "Investigation",
      "Creative writing",
      "Critical thinking",
      "Research skills",
    ],
  },
];

export default cv;
